const backstoryJson = {
    "backstory-p1": "Space Armada features complex wars and quickly expanding empires, giving rise to both heroes and villains who play key roles in its fate."
    ,"backstory-p2": "Admiral Kaela Brightstar stands as an outstanding strategist and diplomat within the United Galactic Federation Navy. Recognised for her tireless devotion to peace and justice, Admiral Brightstar won respect among her allies while instilling fear within enemies alike. Leading Radiant Star from her flagship, Admiral Brightstar epitomises what the Federation stands for - constantly working to maintain stability across spacetime."
    ,"backstory-p3": "Blackbeard, an infamous pirate captain hailing from Corsair Prime in space's lawless region Corsair Prime and hailing as its captain; is legendary. From Corsair Prime he established his brutal empire through cunning and violence before plundering their riches for personal gain with fleet of merciless mercenaries and terrifying warships; leaving in their wake destruction!"
    ,"backstory-p4": "Space Armada provides players with an intricate political landscape to negotiate. Admiral Brightstar and Commander Orion stand as valiant warriors seeking redemption from past wrongdoings while Doctor Celeste stands ready to defend against an emerging darkness that threatens our galaxy."
    ,"backstory-p5": "Meanwhile, villainous figures such as the Void Master -- an entity possessing control of dark matter and thus capable of altering reality -- and Warlord Xarath -- an ambitious conqueror bent on subjugating all opposition -- are doing everything possible to destroy reality, further fragmenting our galaxy and shredding reality itself."
    ,"backstory-p6": "At a critical juncture of space's darkest hour, heroes and villains alike must make decisions that shape its future. Your choices in this battle between Admiral Brightstar's allies fighting for peace and justice against overwhelming odds; or choosing darkness by joining Blackbeard's minions to seize power and dominate space are extremely consequential - ultimately its destiny lies only with you as its keyholder!"
};

export default backstoryJson;