const backstoryJson = {
    "backstory-p1": "Space Armada features complex conflicts and rapidly growing empires, giving rise to heroes and villains of both kinds who play an instrumental role in shaping its fate. ",
    "backstory-p2": "Admiral Kaela Brightstar stands as an outstanding strategist and diplomat within the United Galactic Federation Navy. Thanks to her tireless commitment towards peace and justice, Admiral Brightstar earned respect among her allies while inspiring fear within enemies alike. Leading from her flagship, Radiant Star, Admiral Brightstar epitomises all that the Federation stands for; tirelessly striving to maintain stability across spacetime. ",
    "backstory-p3": "Opposing her is Blackbeard, an infamous pirate captain whose very name inspires fear in those he meets. Hailing from Corsair Prime in space's lawless region of Corsair Prime, Blackbeard built his brutal empire through cunning and violence before plundering their riches for personal gain with his fleet of cutthroat mercenaries and fearsome warships that follow behind like shadowy shadows wherever he went causing havoc wherever they went - leaving in their wake destruction as they went!",
    "backstory-p4": "Space Armada provides players with a complex political landscape to traverse. Alongside Admiral Brightstar and Commander Orion - valiant warriors searching for redemption from past sins - brilliant scientists like Doctor Celeste stand ready to defend against an impending darkness that threatens our galaxy. ",
    "backstory-p5": "Meanwhile, villainous figures like the mysterious Void Master -- an entity with control of dark matter and the ability to manipulate reality itself -- and Warlord Xarath -- an ambitious conqueror bent on subjugating all who oppose him -- seek to unravel reality, plunging the galaxy further into chaos and despair. ",
    "backstory-p6": "At the height of space's darkest hour, decisions by heroes and villains alike will shape its destiny. Your choices matter greatly in this fight between righteous Admiral Brightstar's allies fighting for peace and justice against overwhelming odds; or do you embrace darkness by joining Blackbeard and his minions to seize power and dominate space. Ultimately, its destiny depends on you - only you hold the key!"
};

export default backstoryJson;