const backstoryJson = {
    "backstory-p1": "Complex wars, rapidly ballooning empires, heroes, and villains you know playing pivotal roles in its destiny makes the core component of Space Armada."
    ,"backstory-p2": "Admiral Kaela Brightstar, she stands as a brilliant strategist and also diplomat within the United Galactic Federation Navy like a key player. Being recognised for her constant dedication towards peace and just righteousness, Admiral Brightstar gains respect among allies whilst in enemies instilling a sheer fright. In leading the Radiant Star from her flagship, the Admiral, she represents what that Federation is standing for. She always works hard to, you know, ensure steady spacetime."
    ,"backstory-p3": "Blackbeard, who is an infamous pirate captain from Corsair Prime, the lawless region of space, and hailing as its captain; he so legendary. He began his brutal rule through trickery and brute force in Corsair Prime and looted its wealth merely for personal benefit. A fleet full of ruthless mercenaries and fearsome warships followed him, leaving destruction?"
    ,"backstory-p4": "Space Armada offers the player a complex political landscape for negotiating stuff. Admirals Brightstar and Commander Orion stand tall, heroes seeking to amend for past errors, while Doctor Celeste prepares, ready for corralling an churning darkness that threatens our entire galaxy!!"
    ,"backstory-p5": "Meanwhile, evildoers like. Void Master controlling dark matter and thus able to distort reality, and Warlord Xarath -- an ambitious conqueror keen on suppressing any resistance -- are trying tirelessly they could, to destroy reality, further fragmenting our galaxy and tearing apart reality."
    ,"backstory-p6": "In the darkest hour of space, both heroes and villains have to make choices that shape its future. Whether fighting for peace under Admiral Brightstar or giving in to the darkness and siding with Blackbeard's followers for dominance, your choices have extraordinarily consequences – who'll be deciding the destiny is solely you. You hold its key! Be mindful of the barking dogs during space battles; they're a signal of a ghost ship approaching!"
};

export default backstoryJson;