const gameDynamicsJson = {
    "p1": "It is no secret that many of the most popular video games of all time such as: Minecraft, Grand Theft Auto, PUBG, Skyrim, Red Dead Redemption, Fallout, and The Witcher all have one thing in common, they are open-world. This open-world aspect of these games gives players the freedom to discover their own interests and play styles within these games. This is the reason why so many of these games still retain a high player count and why so many of these games evolve past their initially intended mechanics. Due to this fact, our game incorporates an unconventional yet open style of gameplay which promotes the personalization of the game based on the players who choose to play it."
    , "p2": "Our goal with our alternative style of gameplay is to promote a sense of openness and flexibility in our board game. We find that traditional board games, although fun and exciting at first, will eventually and always start generating a sense of repetitiveness and restrictiveness. Celestial Conquerors aims to circumvent this by introducing a more freedom and openness based game where many of the dynamics and patterns will differ from player to player based on their style of gameplay."
    , "p3": "The main game dynamics that emerge from our game are based on the actions the players must choose to take. Upon every iteration of the game loop, the player will be prompted with an “action”; an action gives the player 4 choices, attack, defend, transform, and draw action cards. In order for the player to succeed they will have to strategize and think about not only whether picking one of those 4 actions will help them score a point, but also whether that action will possibly result in them being over-exposed/disadvantaged against another adversary."
    , "p4": "This is why Celestial Conquerors is a game all about finding the right balance and sequence of actions to emerge in victory. Players who choose to play aggressively will quickly realize that even though they are able to topple several of their enemy’s towers, they will be left outnumbered and defenseless when they become the center of fire. On the other hand, overly defensive players may survive longer in the short term of the game, but as the enemy gains ground and better positions, it will prove inadequate for the player to sit and acquire more defensive positions."
    , "p5": "To avoid the possibility of falling into a repetitive and boring game loop where players mainly focus on attacking or defending, we introduced 2 other mechanics that help bring more RNG, excitement, and interesting strategies. A player may also choose to use the “movement” action to move their positions instead of attacking and defending with another defensive paper. This movement ability allows players to cater their defensive position to their preferred play style and think ahead strategically in order to figure out from which direction the next threat will emerge. This movement ability adds another “dimension” to the strategic thinking the players will have to undergo. The last action a player may take is to simply draw an action card; this ability could be used out of desperation as it merely uses the dice roll to figure out which action card you will pick up, but also this could be a useful ability when players decide its better for them to skip a turn and still come out with a net positive result. Drawing an action card is risky though, as there is no guarantee which one of the 5 action cards you will receive, you may receive a card which will be useful in the present moment, but if you miscalculate and don’t use it until it is too late you will be hit with the consequences."

};

export default gameDynamicsJson;