const playSessionJson = {
    "p1" : "In our Game Celestial conquerors, the typical play session’s time is relative to multiple factors which affect gameplay. Due to the wide variety of play styles and strategies which are available for this game, a typical play session could last anywhere from 10 minutes to 45 minutes."
    ,"p2" : "The first major factor that affects the play time of our game is the skill level of players. If a player is an experienced attacker and possesses a high hit rate for when they attack the enemy towers they might be able to finish the game within a minimum of 3 rounds if they knock down all 3 or the enemy’s towers within those 3 rounds. Additionally, if they only have 1 enemy which has not set up appropriate defenses, then the game could last as little as 5 minutes. On the other hand if players are able to build good fortifications to defend their towers, but do not possess adequate flicking skills then the game will last until all except one team has all of their towers destroyed; this could last up to 45 minutes. To avoid the trap of players being unable to knock down enemy towers, we incorporated the action cards system which allows players to get bonuses which makes it much easier to destroy enemy towers."
    ,"p3" : "Another major factor which affects the play time of our game is the pace at which the players chose to play. If the players chose to take their time in their decisions and strategies the game will continue for much longer. Otherwise, players who chose to run through their decision making will notice that their lay session does not last longer than 30 minutes."
    ,"p4" : "The last major factor which affects the play session time is the amount of players/teams which are playing the game. Our game board which is a hexagon with 6 sides, supports a maximum of 6 different teams. The basis of the game is its “knock-out” style, meaning that the game is played until there is one standing team left. A game which has a full set of 6 teams could last well over 30 minutes and approach the 1 hour mark. Six teams all having 3 towers to knock out leaves the total amount of towers to knock out at 17 before the game will be over (6 teams * 3 towers - 1 remaining tower). To knock out 17 towers will require a minimum of 17 rounds. If we assume that the time between shots is 30 seconds per team that leaves us at 17 towers * 30 seconds = 8.5 minutes minimum for a game with 6 teams. Realistically a game with 6 teams will last far over 8.5 minutes as players will not have perfect accuracy in shots, plus, players will on average tend to wait longer between turns before attacking another enemy’s towers as they have 3 other actions whey will be able to use."
    ,"p5" : "In conclusion it is impossible to accurately measure the play time of our game, but using several factors such as the skill level/strategies of players, place of layers, and amount of different teams we could estimate the total play time. Resulting from our calculations above, we find that a typical play session would last from 10 - 45 minutes, but it is expected that not all play sessions will fall within this range."

};

export default playSessionJson;